package $package.$rootArtifactId;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.rioproject.test.RioTestRunner;
import org.rioproject.test.SetTestManager;
import org.rioproject.test.TestManager;

/**
 * Testing the ${service} service using the Rio test framework
 *
 * @author: Generated by the Rio Archetype
 */
@RunWith(RioTestRunner.class)
public class IT${service}DeployTest extends ITAbstract${service}Test {
	@SetTestManager
    static TestManager testManager;
    $service service;

    @Before
    public void setup() throws Exception {
	    Assert.assertNotNull(testManager);       
        service = ($service)testManager.waitForService(${service}.class); 
    }

    @Test
    public void test1() {
        testService(service);
    }
}
