package org.rioproject.examples.hospital;

import org.rioproject.watch.Calculable;
import org.rioproject.examples.hospital.Doctor;
import org.rioproject.examples.hospital.Doctor.Status;
import org.rioproject.examples.hospital.RuleServiceHelper;
import java.util.List;
import java.lang.Exception;
global org.rioproject.gnostic.DeployedServiceContext context;

declare Calculable
    @role(event)
    @timestamp(date)
end

rule "Doctor Rule"
when
    $count : Calculable(id == "numPatients", value > 3) from entry-point "calculables-stream"
then
    List<Doctor> doctors = context.getServices("Doctors", Doctor.class);
    RuleServiceHelper.doctorNotify(doctors);
end
