package org.rioproject.gnostic;
import org.rioproject.watch.Calculable;
import org.rioproject.gnostic.test.TestService;
global org.rioproject.gnostic.DeployedServiceContext context;
declare Calculable
    @role(event)
    @timestamp(date)
end
rule "Counter Notification Rule"
when
$count : Calculable(id == "notification", value > 25 && < 45) from entry-point "calculables-stream"
then
    System.out.println("===> Test has been notified : "+$count);
    TestService t = context.getService("Test", TestService.class);
    t.executedRHS();
end
