package $package.$rootArtifactId;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.rioproject.cybernode.StaticCybernode;

import java.io.File;
import java.rmi.RemoteException;
import java.util.Arrays;
import java.util.Collection;
import java.util.Map;

/**
 * Testing the ${service} service
 *
 * @author: Generated by the Rio Archetype
 */
@RunWith(Parameterized.class)
public class IT${service}Test extends ITAbstract${service}Test {
    String opstring;
    $service service;

    @Parameterized.Parameters
    public static Collection<Object[]> data() {
        String opstring = System.getProperty("opstring");
        Assert.assertNotNull("no opstring given", opstring);
        return Arrays.asList(new Object[][] {{ opstring }});
    }

    public IT${service}Test(String opstring) {
        this.opstring = opstring;
    }

    @Before
    public void setup() throws Exception {
        StaticCybernode cybernode = new StaticCybernode();
        Map<String, Object> map = cybernode.activate(new File(opstring));
        for (Map.Entry<String, Object> entry : map.entrySet()) {
            String name = entry.getKey();
            Object impl = entry.getValue();
            if (name.equals("$service"))
                service = ($service) impl;
        }
    }

    @Test
    public void test1() {
        testService(service);
    }
}
