package $package.$rootArtifactId;

import org.junit.Assert;

/**
 * Base class for ${service} testing
 *
 * @author: Generated by the Rio Archetype
 */
public abstract class ITAbstract${service}Test {

    void testService($service service) {
        Assert.assertNotNull(service);
        /* Add your testing code here ...*/
    }
}
