package org.rioproject.gnostic;

import org.rioproject.watch.Calculable;

global org.rioproject.gnostic.DeployedServiceContext context;

declare Calculable
    @role(event)
    @timestamp(date)
end

rule "Test Rule"
when
    Calculable(id == "kSessionCounter", value >= 1 ) from entry-point "calculables-stream"
then
    int serviceCount = context.getServiceCount("ExecutionNodeService", "executionNodeService");
    if(serviceCount < 5) {
        System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Scaling!!!");
        context.increment("ExecutionNodeService", "executionNodeService");
    } else {
        System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Have "+serviceCount+" ExecutionNodeServices");
    }
end